apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.security.secrets.configSecret.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
type: Opaque
data:
  KEY_ALIAS: {{ .Values.security.secrets.configSecret.data.KEY_ALIAS | b64enc }}
  LH_INSTANCE_SECRET: {{ .Values.security.secrets.configSecret.data.LH_INSTANCE_SECRET | b64enc }}
  LH_INTERNAL_SECRET: {{ .Values.security.secrets.configSecret.data.LH_INTERNAL_SECRET | b64enc }}
  LH_KEYSTORE_PASSWORD: {{ .Values.security.secrets.configSecret.data.LH_KEYSTORE_PASSWORD | b64enc }}
  LH_S3_ACCESS_KEY: {{ .Values.security.secrets.configSecret.data.LH_S3_ACCESS_KEY | b64enc }}
  LH_S3_SECRET_KEY: {{ .Values.security.secrets.configSecret.data.LH_S3_SECRET_KEY | b64enc }}
  LH_TRUSTSTORE_PASSWORD: {{ .Values.security.secrets.configSecret.data.LH_TRUSTSTORE_PASSWORD | b64enc }}
  env.properties: {{ .Values.security.secrets.configSecret.data.envProperties | b64enc }}