apiVersion: v1
data:
  CONFIG_PATH: /opt/hb/config/config.yaml
  WDP_SERVICE_ID_PATH: /opt/hb/wdp-service-id/service-id-credentials
kind: ConfigMap
metadata:
  name: spark-hb-deployer-agent-env-config
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "5"