apiVersion: v1
kind: Service
metadata:
  name: {{ include "wxd.fullname" . }}
  labels:
    {{- include "wxd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.ports.console.port }}
    targetPort: console
    protocol: TCP
    name: console
  - port: {{ .Values.service.ports.minio.port }}
    targetPort: minio
    protocol: TCP
    name: minio
  - port: {{ .Values.service.ports.mds.port }}
    targetPort: mds
    protocol: TCP
    name: mds
  selector:
    {{- include "wxd.selectorLabels" . | nindent 4 }}
